# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a87cc2168dc5c3548bed4653e926a7e7f2718752bcd60cbc22ee25ea4a3dd0fbd4146badddb0ad1312f577247acd40e4aea1280d1c7e153ab0602a18b8454c42

test:
  secret_key_base: 6f1cefb9e54feef1046d66cc4574de39c5e459f374249fbf201927edfb927a8363bc75165b382f7c8023f24014ab8ef3e4119a4799a8a41ed1e8d2065c2c1086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
